name: push main branche

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Set namespace
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACEEESSKEY }}
          aws-region: cn-northwest-1
          role-to-assume: ${{ secrets.AWSROLETOASSUME }}
          role-external-id: ${{ secrets.AWSROLEEXTERNALID }}
          role-duration-seconds: 1200
          role-session-name: GitHubActionsSession

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name coloseo

      - name: Set kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Apply kustomize
        run: kustomize build overlays/staging | kubectl apply -f -
